name: galaxy-diffusion-release
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.40.0=h753d276_0
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.0.8=h0b41bf4_0
  - pip=23.3.1=pyhd8ed1ab_0
  - python=3.10.9=he550d4f_0_cpython
  - readline=8.1.2=h0f457ee_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.0.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - cachetools==5.3.2
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - chex==0.1.7
      - click==8.1.7
      - cloudpickle==3.0.0
      - clu==0.0.10
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - corrfunc==2.5.1
      - cycler==0.12.1
      - decorator==5.1.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.5.2
      - flatbuffers==23.5.26
      - flax==0.7.5
      - fonttools==4.45.1
      - fsspec==2023.10.0
      - future==0.18.3
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.24.0
      - google-auth-oauthlib==1.1.0
      - google-pasta==0.2.0
      - grpcio==1.59.3
      - h5py==3.10.0
      - idna==3.6
      - importlib-resources==6.1.1
      - jax==0.4.20
      - jaxlib==0.4.20+cuda12.cudnn89
      - jraph==0.0.6.dev0
      - keras==2.15.0
      - kiwisolver==1.4.5
      - libclang==16.0.6
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - msgpack==1.0.7
      - nest-asyncio==1.5.8
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.3.4.1
      - nvidia-cuda-cupti-cu12==12.3.101
      - nvidia-cuda-nvcc-cu12==12.3.103
      - nvidia-cuda-nvrtc-cu12==12.3.103
      - nvidia-cuda-runtime-cu12==12.3.101
      - nvidia-cudnn-cu12==8.9.6.50
      - nvidia-cufft-cu12==11.0.12.1
      - nvidia-cusolver-cu12==11.5.4.101
      - nvidia-cusparse-cu12==12.2.0.103
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optax==0.1.7
      - orbax-checkpoint==0.4.4
      - packaging==23.2
      - pandas==2.1.3
      - pillow==10.1.0
      - protobuf==4.23.4
      - psutil==5.9.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycorr==1.0.0
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rsa==4.9
      - scipy==1.11.4
      - sentry-sdk==1.38.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-probability==0.23.0
      - tensorstore==0.1.50
      - termcolor==2.4.0
      - toolz==0.12.0
      - tqdm==4.66.1
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - wandb==0.16.0
      - werkzeug==3.0.1
      - wrapt==1.14.1
      - wurlitzer==3.0.3
      - zipp==3.17.0
prefix: /n/holystore01/LABS/iaifi_lab/Users/smsharma/envs/galaxy-diffusion-release
